# frozen_string_literal: true

# Wrapper for 'SDL_video.h'
# Handles Display and Window Management
#
module SDL3
  PROP_GLOBAL_VIDEO_WAYLAND_WL_DISPLAY_POINTER = 'SDL.video.wayland.wl_display'

  WINDOW_FULLSCREEN          = 0x0000000000000001
  WINDOW_OPENGL              = 0x0000000000000002
  WINDOW_OCCLUDED            = 0x0000000000000004
  WINDOW_HIDDEN              = 0x0000000000000008
  WINDOW_BORDERLESS          = 0x0000000000000010
  WINDOW_RESIZABLE           = 0x0000000000000020
  WINDOW_MINIMIZED           = 0x0000000000000040
  WINDOW_MAXIMIZED           = 0x0000000000000080
  WINDOW_MOUSE_GRABBED       = 0x0000000000000100
  WINDOW_INPUT_FOCUS         = 0x0000000000000200
  WINDOW_MOUSE_FOCUS         = 0x0000000000000400
  WINDOW_EXTERNAL            = 0x0000000000000800
  WINDOW_MODAL               = 0x0000000000001000
  WINDOW_HIGH_PIXEL_DENSITY  = 0x0000000000002000
  WINDOW_MOUSE_CAPTURE       = 0x0000000000004000
  WINDOW_MOUSE_RELATIVE_MODE = 0x0000000000008000
  WINDOW_ALWAYS_ON_TOP       = 0x0000000000010000
  WINDOW_UTILITY             = 0x0000000000020000
  WINDOW_TOOLTIP             = 0x0000000000040000
  WINDOW_POPUP_MENU          = 0x0000000000080000
  WINDOW_KEYBOARD_GRABBED    = 0x0000000000100000
  WINDOW_VULKAN              = 0x0000000010000000
  WINDOW_METAL               = 0x0000000020000000
  WINDOW_TRANSPARENT         = 0x0000000040000000
  WINDOW_NOT_FOCUSABLE       = 0x0000000080000000

  WINDOWPOS_UNDEFINED_MASK = 0x1FFF0000
  WINDOWPOS_CENTERED_MASK  = 0x2FFF0000

  GL_CONTEXT_PROFILE_CORE          = 0x0001
  GL_CONTEXT_PROFILE_COMPATIBILITY = 0x0002
  GL_CONTEXT_PROFILE_ES            = 0x0004

  GL_CONTEXT_DEBUG_FLAG              = 0x0001
  GL_CONTEXT_FORWARD_COMPATIBLE_FLAG = 0x0002
  GL_CONTEXT_ROBUST_ACCESS_FLAG      = 0x0004
  GL_CONTEXT_RESET_ISOLATION_FLAG    = 0x0008

  GL_CONTEXT_RELEASE_BEHAVIOR_NONE  = 0x0000
  GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH = 0x0001

  GL_CONTEXT_RESET_NO_NOTIFICATION = 0x0000
  GL_CONTEXT_RESET_LOSE_CONTEXT    = 0x0001

  PROP_DISPLAY_HDR_ENABLED_BOOLEAN             = 'SDL.display.HDR_enabled'
  PROP_DISPLAY_KMSDRM_PANEL_ORIENTATION_NUMBER = 'SDL.display.KMSDRM.panel_orientation'
  PROP_DISPLAY_WAYLAND_WL_OUTPUT_POINTER       = 'SDL.display.wayland.wl_output'

  PROP_WINDOW_CREATE_ALWAYS_ON_TOP_BOOLEAN = 'SDL.window.create.always_on_top'
  PROP_WINDOW_CREATE_BORDERLESS_BOOLEAN = 'SDL.window.create.borderless'
  PROP_WINDOW_CREATE_CONSTRAIN_POPUP_BOOLEAN = 'SDL.window.create.constrain_popup'
  PROP_WINDOW_CREATE_FOCUSABLE_BOOLEAN = 'SDL.window.create.focusable'
  PROP_WINDOW_CREATE_EXTERNAL_GRAPHICS_CONTEXT_BOOLEAN = 'SDL.window.create.external_graphics_context'
  PROP_WINDOW_CREATE_FLAGS_NUMBER = 'SDL.window.create.flags'
  PROP_WINDOW_CREATE_FULLSCREEN_BOOLEAN = 'SDL.window.create.fullscreen'
  PROP_WINDOW_CREATE_HEIGHT_NUMBER = 'SDL.window.create.height'
  PROP_WINDOW_CREATE_HIDDEN_BOOLEAN = 'SDL.window.create.hidden'
  PROP_WINDOW_CREATE_HIGH_PIXEL_DENSITY_BOOLEAN = 'SDL.window.create.high_pixel_density'
  PROP_WINDOW_CREATE_MAXIMIZED_BOOLEAN = 'SDL.window.create.maximized'
  PROP_WINDOW_CREATE_MENU_BOOLEAN = 'SDL.window.create.menu'
  PROP_WINDOW_CREATE_METAL_BOOLEAN = 'SDL.window.create.metal'
  PROP_WINDOW_CREATE_MINIMIZED_BOOLEAN = 'SDL.window.create.minimized'
  PROP_WINDOW_CREATE_MODAL_BOOLEAN = 'SDL.window.create.modal'
  PROP_WINDOW_CREATE_MOUSE_GRABBED_BOOLEAN = 'SDL.window.create.mouse_grabbed'
  PROP_WINDOW_CREATE_OPENGL_BOOLEAN = 'SDL.window.create.opengl'
  PROP_WINDOW_CREATE_PARENT_POINTER = 'SDL.window.create.parent'
  PROP_WINDOW_CREATE_RESIZABLE_BOOLEAN = 'SDL.window.create.resizable'
  PROP_WINDOW_CREATE_TITLE_STRING = 'SDL.window.create.title'
  PROP_WINDOW_CREATE_TRANSPARENT_BOOLEAN = 'SDL.window.create.transparent'
  PROP_WINDOW_CREATE_TOOLTIP_BOOLEAN = 'SDL.window.create.tooltip'
  PROP_WINDOW_CREATE_UTILITY_BOOLEAN = 'SDL.window.create.utility'
  PROP_WINDOW_CREATE_VULKAN_BOOLEAN = 'SDL.window.create.vulkan'
  PROP_WINDOW_CREATE_WIDTH_NUMBER = 'SDL.window.create.width'
  PROP_WINDOW_CREATE_X_NUMBER = 'SDL.window.create.x'
  PROP_WINDOW_CREATE_Y_NUMBER = 'SDL.window.create.y'
  PROP_WINDOW_CREATE_COCOA_WINDOW_POINTER = 'SDL.window.create.cocoa.window'
  PROP_WINDOW_CREATE_COCOA_VIEW_POINTER = 'SDL.window.create.cocoa.view'
  PROP_WINDOW_CREATE_WAYLAND_SURFACE_ROLE_CUSTOM_BOOLEAN = 'SDL.window.create.wayland.surface_role_custom'
  PROP_WINDOW_CREATE_WAYLAND_CREATE_EGL_WINDOW_BOOLEAN = 'SDL.window.create.wayland.create_egl_window'
  PROP_WINDOW_CREATE_WAYLAND_WL_SURFACE_POINTER = 'SDL.window.create.wayland.wl_surface'
  PROP_WINDOW_CREATE_WIN32_HWND_POINTER = 'SDL.window.create.win32.hwnd'
  PROP_WINDOW_CREATE_WIN32_PIXEL_FORMAT_HWND_POINTER = 'SDL.window.create.win32.pixel_format_hwnd'
  PROP_WINDOW_CREATE_X11_WINDOW_NUMBER = 'SDL.window.create.x11.window'
  PROP_WINDOW_CREATE_EMSCRIPTEN_CANVAS_ID_STRING = 'SDL.window.create.emscripten.canvas_id'
  PROP_WINDOW_CREATE_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING = 'SDL.window.create.emscripten.keyboard_element'

  PROP_WINDOW_SHAPE_POINTER = 'SDL.window.shape'
  PROP_WINDOW_HDR_ENABLED_BOOLEAN = 'SDL.window.HDR_enabled'
  PROP_WINDOW_SDR_WHITE_LEVEL_FLOAT = 'SDL.window.SDR_white_level'
  PROP_WINDOW_HDR_HEADROOM_FLOAT = 'SDL.window.HDR_headroom'
  PROP_WINDOW_ANDROID_WINDOW_POINTER = 'SDL.window.android.window'
  PROP_WINDOW_ANDROID_SURFACE_POINTER = 'SDL.window.android.surface'
  PROP_WINDOW_UIKIT_WINDOW_POINTER = 'SDL.window.uikit.window'
  PROP_WINDOW_UIKIT_METAL_VIEW_TAG_NUMBER = 'SDL.window.uikit.metal_view_tag'
  PROP_WINDOW_UIKIT_OPENGL_FRAMEBUFFER_NUMBER = 'SDL.window.uikit.opengl.framebuffer'
  PROP_WINDOW_UIKIT_OPENGL_RENDERBUFFER_NUMBER = 'SDL.window.uikit.opengl.renderbuffer'
  PROP_WINDOW_UIKIT_OPENGL_RESOLVE_FRAMEBUFFER_NUMBER = 'SDL.window.uikit.opengl.resolve_framebuffer'
  PROP_WINDOW_KMSDRM_DEVICE_INDEX_NUMBER = 'SDL.window.kmsdrm.dev_index'
  PROP_WINDOW_KMSDRM_DRM_FD_NUMBER = 'SDL.window.kmsdrm.drm_fd'
  PROP_WINDOW_KMSDRM_GBM_DEVICE_POINTER = 'SDL.window.kmsdrm.gbm_dev'
  PROP_WINDOW_COCOA_WINDOW_POINTER = 'SDL.window.cocoa.window'
  PROP_WINDOW_COCOA_METAL_VIEW_TAG_NUMBER = 'SDL.window.cocoa.metal_view_tag'
  PROP_WINDOW_OPENVR_OVERLAY_ID_NUMBER = 'SDL.window.openvr.overlay_id'
  PROP_WINDOW_VIVANTE_DISPLAY_POINTER = 'SDL.window.vivante.display'
  PROP_WINDOW_VIVANTE_WINDOW_POINTER = 'SDL.window.vivante.window'
  PROP_WINDOW_VIVANTE_SURFACE_POINTER = 'SDL.window.vivante.surface'
  PROP_WINDOW_WIN32_HWND_POINTER = 'SDL.window.win32.hwnd'
  PROP_WINDOW_WIN32_HDC_POINTER = 'SDL.window.win32.hdc'
  PROP_WINDOW_WIN32_INSTANCE_POINTER = 'SDL.window.win32.instance'
  PROP_WINDOW_WAYLAND_DISPLAY_POINTER = 'SDL.window.wayland.display'
  PROP_WINDOW_WAYLAND_SURFACE_POINTER = 'SDL.window.wayland.surface'
  PROP_WINDOW_WAYLAND_VIEWPORT_POINTER = 'SDL.window.wayland.viewport'
  PROP_WINDOW_WAYLAND_EGL_WINDOW_POINTER = 'SDL.window.wayland.egl_window'
  PROP_WINDOW_WAYLAND_XDG_SURFACE_POINTER = 'SDL.window.wayland.xdg_surface'
  PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_POINTER = 'SDL.window.wayland.xdg_toplevel'
  PROP_WINDOW_WAYLAND_XDG_TOPLEVEL_EXPORT_HANDLE_STRING = 'SDL.window.wayland.xdg_toplevel_export_handle'
  PROP_WINDOW_WAYLAND_XDG_POPUP_POINTER = 'SDL.window.wayland.xdg_popup'
  PROP_WINDOW_WAYLAND_XDG_POSITIONER_POINTER = 'SDL.window.wayland.xdg_positioner'
  PROP_WINDOW_X11_DISPLAY_POINTER = 'SDL.window.x11.display'
  PROP_WINDOW_X11_SCREEN_NUMBER = 'SDL.window.x11.screen'
  PROP_WINDOW_X11_WINDOW_NUMBER = 'SDL.window.x11.window'
  PROP_WINDOW_EMSCRIPTEN_CANVAS_ID_STRING = 'SDL.window.emscripten.canvas_id'
  PROP_WINDOW_EMSCRIPTEN_KEYBOARD_ELEMENT_STRING = 'SDL.window.emscripten.keyboard_element'

  WINDOW_SURFACE_VSYNC_DISABLED = 0
  WINDOW_SURFACE_VSYNC_ADAPTIVE = -1

  # --- Function Attachments ---

  attach_function :get_num_video_drivers, :SDL_GetNumVideoDrivers, [], :int
end
